(ns unwired-epistemology.main
  (:require [unwired-epistemology.application.bootstrap :as application]
            [unwired-epistemology.platform.secure-identity :as identity]
            [unwired-epistemology.platform.flutter.view :as view]))

(defn ^:async main []
  (await
    (application/start {:view/initialize! view/initialize!
                        :view/render! view/render!
                        :identity/ports! identity/ports})))
