(ns unwired-epistemology.main
  (:require [unwired-epistemology.application.bootstrap :as application]
            [unwired-epistemology.platform.secure-identity :as identity]
            [unwired-epistemology.platform.invitation-codec :as invitation-codec]
            [unwired-epistemology.platform.deep-links :as deep-links]
            [unwired-epistemology.platform.hybrid-peers :as hybrid-peers]
            [unwired-epistemology.platform.flutter.view :as view]))

(defn ^:async main []
  (await
    (application/start
      (merge {:view/initialize! view/initialize!
              :view/render! view/render!
              :identity/ports! identity/ports
              :links/ports! deep-links/ports}
             (invitation-codec/ports)
             (hybrid-peers/ports)))))
